### ISSUE TITLE
Can't fetch image files

### ISSUE THREAD

**Issue by Modedrain** [dillonplunkett/bazaar#1]
Hi,

Following your guide, I get this error when trying to fetch files:
$ python fetch_images.py

Output stays on the first card, nothing happens. On keyboard interrupt i get this:

Traceback (most recent call last):
  File "fetch_images.py", line 20, in <module>
    image_url = urlopen(redir_to_image).geturl()
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)

Any ideas?

Thanks!

**Comment by Modedrain** [comment]
Update: running the script for about 30 minutes gets me one image. Then it moves on to the next and gets stuck again.

**Comment by dillonplunkett** [comment]
Hi, 

I haven't been able to reproduce this issue yet. A couple of things that might help me track it down:
- Do you get it with the example `cube_list.txt` that's included? 
- Can you successfully access the Scryfall API (e.g., [this URL](https://api.scryfall.com/cards/named?fuzzy=preordain&format=image&version=normal)) from the machine where you have this problem? 
- Do you get the same issue using Python 3.6?

**Comment by Modedrain** [comment]
I tried both the supplied cube list as well as my own - no difference.

I had no problem accessing the scryfall API referred to in the script through my browser. Sorry, I should have left this information in the original post.

I'll try Python 3.6 once i get home tonight. Thanks!

**Comment by Modedrain** [comment]
Problem persists on python 3.6:

(.venv) [torkel@greta-loonix bazaar]$ python3.6 fetch_images.py 
Champion of the Parish
^CTraceback (most recent call last):
  File "fetch_images.py", line 20, in <module>
    image_url = urlopen(redir_to_image).geturl()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1415, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
KeyboardInterrupt

**Comment by dillonplunkett** [comment]
Got it. 

Next idea: Are you connected to the internet via a proxy?

**Comment by dillonplunkett** [comment]
Closed this by accident.

**Comment by Modedrain** [comment]
Unfortunately, problem persists even with my router disconnected - computer directly to internet. No proxy or vpn. I'll try the script out on another machine and get back to you.

**Comment by Modedrain** [comment]
Worked on another machine. Something off with mine obviously, closing this. Thanks
